# Chapter 1

## Pytorch fundamentals


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


### Tensors

#### Creation


In [ ]:
## Intro to tensors


### Creating tensors

scalar = torch.tensor(7)

scalar


tensor(7)

In [ ]:
 scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,2])

vector

tensor([7, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matric

MATRIX = torch.tensor([[1,2],
                       [3,2]])

MATRIX

tensor([[1, 2],
        [3, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,43],
                        [34,56,7],
                        [3,2,1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][1]

tensor([34, 56,  7])

In [ ]:
TENSOR = torch.tensor([ [ [1, 2,3],
                         [4, 5, 6],
                          [7, 8, 9]
                          ],
                           [
                               [11, 12, 13],
                                [14, 15, 16],
                                [17, 18, 19 ]
                               ]
                        ])

In [ ]:
  TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

#### Random tensors

In [ ]:
# Create random tensor

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.8591, 0.6640, 0.3724, 0.4964],
        [0.7811, 0.6143, 0.0316, 0.3220],
        [0.7587, 0.4265, 0.8540, 0.3201]])

In [ ]:
# Create random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channel (R, G, B), height, width of the images

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# Zeros
zeros  = torch.zeros(size = (3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Ones

ones = torch.ones(size = (3,4))

ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# using range of tensors

ranged_tensor  = torch.arange(start = 0, end = 10, step = 2)

ranged_tensor

tensor([0, 2, 4, 6, 8])

In [ ]:
# Creating tensor-like

ranged_tensor_like = torch.zeros_like(input = ranged_tensor)

ranged_tensor_like

tensor([0, 0, 0, 0, 0])

In [ ]:
# like tensor creating same shape tensor like input = must_be_tensor

print(f"The input tensor shape: {ranged_tensor.shape}, the like created tensor shape: {ranged_tensor_like.shape}")

The input tensor shape: torch.Size([5]), the like created tensor shape: torch.Size([5])


#### Tensor attributes

**Note**:  three important and most common errors in deep learning is
1. tensor dtype mismatch - `torch.dtype`
2. tensor device type mismatch - `torch.shape`
3. tensor shape mismatch - `torch.device`

In [ ]:
# Float 32

float_32_tensor = torch.tensor([3.0, 2.0, 1.0],
                               dtype=None,  # data type
                               device = None, # What device that your tensor on
                               requires_grad = False) # Whether to tract gradients with this tensor operations

float_32_tensor

tensor([3., 2., 1.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 2., 1.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([9., 4., 1.])

some operation between different dtype tensor can be done. but be aware during deep learning and training it may cause an error.




In [ ]:
# Getting information about the tensor

random_tensor = torch.rand(size = (3,4))
print(f"Shape of the tensor: {random_tensor.shape}")
print(f"Datatype of the tensor: {random_tensor.dtype}")
print(f"Device of the tensor: {random_tensor.device}")

Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device of the tensor: cpu


#### Manipulation of Tensors (tensor operations)

In [ ]:
# Addition

## with constant value

tensor1 = torch.tensor([1,2,3])

const  = 10

print("Addition operation with constant")

### using symbol +

print(tensor1 + const)

### using torch method

print(torch.add(tensor1, const))

print("Addition operation bw two tensor")
## with another tensor

tensor2 = torch.tensor([2,4,6])

### using symbol +

print(tensor1+ tensor2)

### using torch method

print(torch.add(tensor1, tensor2))

Addition operation with constant
tensor([11, 12, 13])
tensor([11, 12, 13])
Addition operation bw two tensor
tensor([3, 6, 9])
tensor([3, 6, 9])


In [ ]:
# Substraction

tensor1 = torch.tensor([10, 20, 30])

## with constant

const  =  5

print("Substraction with constant")

### using symbol -

print(tensor1 - const)

### using torch method

print(torch.sub(tensor1 ,  const))

## with another tensor

tensor2 = torch.tensor([5,6,7])

print("Substraction with another tensor")

### using symbol -

print(tensor1 - tensor2)

### using torch method

print(torch.sub(tensor1, tensor2))

Substraction with constant
tensor([ 5, 15, 25])
tensor([ 5, 15, 25])
Substraction with another tensor
tensor([ 5, 14, 23])
tensor([ 5, 14, 23])


In [ ]:
# Multiplication - two ways of multiplication (normal multiplication / matrix multiplication)

tensor1 = torch.tensor([1,2,3])

## with constant (scalar)

scalar = 10

print("Multiplication with scalar")

### using symbol *

print(tensor1 * scalar)

### using torch method

print(torch.mul(tensor1, scalar))

## with another tensor

print("Multiplication with another tensor")

tensor2 = torch.tensor([2, 4, 6])

### using symbol *

print(tensor1 * tensor2)

### using torch method

print(torch.mul(tensor1, tensor2))

Multiplication with scalar
tensor([10, 20, 30])
tensor([10, 20, 30])
Multiplication with another tensor
tensor([ 2,  8, 18])
tensor([ 2,  8, 18])


In [ ]:
# Matrix multiplication (dot product)

tensor1 = torch.tensor([[1,2,3],[4,5,7],[9,8,1]])

transformation = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])

print("Matrix Multiplication-  where order of tensor matters")

## using torch method

print(torch.matmul(tensor1, transformation))

## order 2

print(torch.mm(transformation, tensor1)) ## torch.mm is alias of matmul

print("Its not equal because matrix multiplication is associative, means A.B != B.A")

Matrix Multiplication-  where order of tensor matters
tensor([[14, 14, 14],
        [35, 35, 35],
        [28, 28, 28]])
tensor([[14, 15, 11],
        [28, 30, 22],
        [42, 45, 33]])
Its not equal because matrix multiplication is associative, means A.B != B.A


In [ ]:
# Transpose


tensor1 = torch.rand(size = (3,2))

print(f"tensor1 : {tensor1}, shape: {tensor1.shape}")

# transposing

print(tensor1.T.shape)

tensor1 : tensor([[0.5922, 0.2579],
        [0.0388, 0.8672],
        [0.0689, 0.5796]]), shape: torch.Size([3, 2])
torch.Size([2, 3])


### Tensor aggregation

In [ ]:
# Creating the tensor


tensor = torch.arange(0,100,1)

## min - tensor.min() or torch.min(tensor)

print(f"The minimum value of tensor: {torch.min(tensor)}")

## max - tensor.max() or torch.max(tensor)

print(f"The maximun value of tensor: {torch.max(tensor)}")

## mean - tensor.mean() or torch.mean(tensor)

print(f"The mean value of tensor: {torch.mean(tensor.type(torch.float32))}")


## sum -  tensor.sum() or torch.sum(tensor)

print(f"The summation of tensor: {torch.sum(tensor)}")

The minimum value of tensor: 0
The maximun value of tensor: 99
The mean value of tensor: 49.5
The summation of tensor: 4950


In [ ]:
# Positional min, max (argmin, argmax)

## position of minimun value - tensor.argmin() or torch.argmin(tensor)

print(f"The index of minimum value in the tensor: {torch.argmin(tensor)}")

## position of maximum value -  tensor.argmax() or torch.argmax(tensor)

print(f"The index of the maximum value in the tensor: {torch.argmax(tensor)}")


The index of minimum value in the tensor: 0
The index of the maximum value in the tensor: 99


In [ ]:
# Reshaping and view, stacking, squeezing and unsqueezing tensors


tensor = torch.arange(0, 12)

print(f"The tensor: {tensor} with shape and length:{tensor.shape}, {len(tensor)}")

## Reshaping

tensor_reshaped = tensor.reshape(4,3)

print(tensor_reshaped)

The tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) with shape and length:torch.Size([12]), 12
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [ ]:
## View

### view is copy of the tensor with customised shape

z = tensor_reshaped.view(3,4) # think like `view` as pointer of some tensor

print(z)

### z and tensor_reshaped has same memory. means changes `z` changes `tensor_reshaped` and viceversa

z[0, 1] = 10

print("after the z[0,1] = 10")

print(f"z: {z}")

print(f"tensor_reshaped: {tensor_reshaped}")

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
after the z[0,1] = 10
z: tensor([[ 0, 10,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor_reshaped: tensor([[ 0, 10,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [ ]:
# Stacking

print(f"Stacked tensor: {tensor_reshaped}, with shape {tensor_reshaped.shape}")

## dim= 0 (vertical stack) like adding rows together axis = 0

stacked = torch.stack((tensor_reshaped, z.reshape(4,3)), dim= 0)

print(f"vertically stacked : {stacked}, and shape: {stacked.shape}")


## dim = 1 (horizondal stack) like adding new columns axis = 1

stacked = torch.stack((tensor_reshaped, z.reshape(4,3)), dim = 1)

print(f"Horizodally stacked: {stacked}, and shape: {stacked.shape}")

Stacked tensor: tensor([[ 0, 10,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), with shape torch.Size([4, 3])
vertically stacked : tensor([[[ 0, 10,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[ 0, 10,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]), and shape: torch.Size([2, 4, 3])
Horizodally stacked: tensor([[[ 0, 10,  2],
         [ 0, 10,  2]],

        [[ 3,  4,  5],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [ 9, 10, 11]]]), and shape: torch.Size([4, 2, 3])


In [ ]:
# Squeeze

tensor = torch.arange(0,10).reshape(1,10)
## removes all the single dimension from target tensor

print(f"tensor used: {tensor}, shape : {tensor.shape}")


tensor_squeezed = torch.squeeze(tensor)

print(f"The squeezed tensor: {tensor_squeezed}, Shape: {tensor_squeezed.shape}")


## unsqueezing

tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim = 0)

print(f"The Unsqueezed tensor: {tensor_unsqueezed}, Shape: {tensor_unsqueezed.shape}")

tensor used: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), shape : torch.Size([1, 10])
The squeezed tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), Shape: torch.Size([10])
The Unsqueezed tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), Shape: torch.Size([1, 10])


In [ ]:
# Permute

tensor = torch.rand(size = (1,2,3))

print(f"Tensor used:{tensor}, shape: {tensor.shape} ")

## Rearrange tensor axis order - premuted tensor and output tensor shares the same memory

tensor_premuted = tensor.permute(2,0,1) # or torch.premute(tensor, dims)

print(f"Tensor premuted to 2,0,1 : {tensor_premuted}, shape: {tensor_premuted.shape}")


Tensor used:tensor([[[0.4624, 0.9870, 0.0885],
         [0.2516, 0.8704, 0.0645]]]), shape: torch.Size([1, 2, 3]) 
Tensor premuted to 2,0,1 : tensor([[[0.4624, 0.2516]],

        [[0.9870, 0.8704]],

        [[0.0885, 0.0645]]]), shape: torch.Size([3, 1, 2])


### Indexing

In [ ]:
 # Indexing -same as numPy

tensor = torch.arange(1,19).reshape(2,3,3)


## index starts from `0`

print(f"The tensor used: \n{tensor}")

print("---")
print(f"tensor[0]: \n{tensor[0]}")
print("---")
print(f"tensor[0][0]: \n{tensor[0][0]}")
print("---")
print(f"tensor[0][0][0]: \n{tensor[0][0][0]}")




The tensor used: 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
---
tensor[0]: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
---
tensor[0][0]: 
tensor([1, 2, 3])
---
tensor[0][0][0]: 
1


In [ ]:
# Using :

# tensor has shape(2, 3, 3) so index range  [:2, :3, :3]

tensor[:2, :2, :3]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 11, 12],
         [13, 14, 15]]])

In [ ]:
tensor[:2, 1:3, 1:3]

tensor([[[ 5,  6],
         [ 8,  9]],

        [[14, 15],
         [17, 18]]])

### Pytorch and numpy

In [ ]:
# we can convert torch tensor into numpy array

## tensor

tensor =  torch.arange(1,10).reshape(1,3,3).type(dtype = torch.int32)

## converting into numpy array

numpy_array = tensor.numpy()

print(f"Tensor used: {tensor} with {tensor.dtype}") # data types --> float 64

print(f"Numpy array: {numpy_array} with {numpy_array.dtype}") # data types --> float 64

Tensor used: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32) with torch.int32
Numpy array: [[[1 2 3]
  [4 5 6]
  [7 8 9]]] with int32


In [ ]:
# creating tensor from numpy array

array = np.arange(1, 10).reshape(3,3)

print(f"\nThe array used: {array}, \tdtype:{array.dtype} ")

## convertion

tensor = torch.from_numpy(array)


print(f"\nThe converted tensor: {tensor}, \tdtype:{tensor.dtype}")


The array used: [[1 2 3]
 [4 5 6]
 [7 8 9]], 
dtype:int64 

The converted tensor: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), 	dtype:torch.int64


### Randomness

In [ ]:
# torch.manual_seed(seed = RANDOM_SEED)


## why - neural networks initial weights are fixed randomly. then after the experiments, how to reproduce the same results with random weights. we can control randomness


### example
print("\nDefault randomness in  action")
print(f"\nTensor 1: {torch.rand(2,2)}")
print(f"\nTensor 2: {torch.rand(2,2)}")

### setting controlled randomness

print(f"\nControlled randomness in action with seed 64")

torch.random.manual_seed(seed=64) # this value reset for every random call
print(f"\nTensor 1: {torch.rand(2,2)}")

torch.random.manual_seed(seed=64)
print(f"\nTensor 2: {torch.rand(2,2)}")

#### changing the seed

print(f"\nControlled randomness in action with seed 46")

torch.random.manual_seed(seed=46)
print(f"\nTensor 1: {torch.rand(2,2)}")

torch.random.manual_seed(seed=46)
print(f"\nTensor 2: {torch.rand(2,2)}")


Default randomness in  action

Tensor 1: tensor([[0.4717, 0.8384],
        [0.1639, 0.1899]])

Tensor 2: tensor([[0.9971, 0.5516],
        [0.7827, 0.1247]])

Controlled randomness in action with seed 64

Tensor 1: tensor([[0.0492, 0.5989],
        [0.1771, 0.2639]])

Tensor 2: tensor([[0.0492, 0.5989],
        [0.1771, 0.2639]])

Controlled randomness in action with seed 46

Tensor 1: tensor([[0.6611, 0.0600],
        [0.5174, 0.1596]])

Tensor 2: tensor([[0.6611, 0.0600],
        [0.5174, 0.1596]])


#### GPU and CPU  and agnostic code

In [ ]:
# ## checking availability of GPU

# !nvidia-smi  --> checking whether GPU hardware available

# torch.cuda.is_available() --> checking pytorch recognises the GPU hardware if available

# ## setting the pytorch on GPU if available


# device  =  "cuda" if torch.cuda.is_available() else "cpu"

# print(device)

cpu


`device` parameter determines whether the computations run using cpu or gpu. so we need to save the input(tensors), model in gpu/ cpu (device) for seamless computation. there are different ways to achieve this as follows


In [ ]:
# ## Method 1: setting up device dynamically

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ## Method 2 : moving tensors and models to device manually

# tensor = torch.rand(2,3)

# tensor = tensor.to(device)

# ## Method 3: device aware tensor initialisation

# tensor = torch.rand(size = (2,3), device = device)

# print(f"Total gpu devices available: {torch.cuda.device_count()}")

In [ ]:
# # apple silicon

# torch.backends.mps.is_available() # returns true for apple silicon

# # setting device type

# device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

In [ ]:
## moving back to cpu

### numpy doesnt utilize the gpu, so we to copy tensors from gpu to cpu to convert it into numpy

tensor_in_gpu = torch.rand(size = (2,2), device = device)

tensor  = tensor_in_gpu.cpu()

array  = tensor.numpy()

array

array([[0.44815624, 0.9998031 ],
       [0.3220119 , 0.7413921 ]], dtype=float32)

# Chapter 2  

# Pytorch workflows